### ISSUE TITLE
Feature: Make Channel Mod modification easier

### ISSUE THREAD

**Issue by apex-omontgomery** [OperationCode/operationcode-pyback#1]
# Description

Channel name, workspace, and display name should be sufficient to do the rest. This could even be an admin slash command or an interactive form. 

# Purpose

If something happens and we need more channel mods, we want this to be easy.

**Comment by AllenAnthes** [comment]
I'm assuming we can just scrap this feature as it didn't really take off?

**Comment by apex-omontgomery** [comment]
Right now they just gave people admin. But I think in the future formal channel mods would be great.
