### ISSUE TITLE
Update github notifications

### ISSUE THREAD

**Issue by apex-omontgomery** [OperationCode/operationcode-pyback#2]
old:
`@hpjaj ,@wimo7083 ,@jhampton ,@kylemh ,@davidmolina ,@nellshamrell ,@hollomancer ,@maggi-oc ,`

new:
`@wimo7083 ,@jhampton ,@kylemh `

**Comment by steaksauce-** [comment]
I'd like to take a look at this. I've been poking around the repo and can't seem to find the file that this resides in though.

**Comment by apex-omontgomery** [comment]
https://github.com/OperationCode/operationcode-pyback/blob/0a9e6bb98a62c83ef2a0117d946ea84e80c42273/src/frontend/views.py#L53

There's something screwy going on the users are commented out but:
https://github.com/OperationCode/operationcode_backend/issues/430

Has them being entered. If you'd like to go ahead and change that line and uncomment it I'll merge when I figure out what's going on.

**Comment by steaksauce-** [comment]
Created #3 for this.
